name = "uCSV"
uuid = "e0b4c2ea-889f-54df-a5e0-fe74b3c892fd"
authors = ["Cameron Prybol <cameron.prybol@gmail.com>"]
version = "0.1.5"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.0"
DataFrames = "1.0"
